dpi: 100

cursor-size: 32

alacritty:
  point-size: 11
  colours: |2
      # Colors (Pencil Dark)
      colors:
        # Default Colors
        primary:
          background: '0x212121'
          foreground: '0xf1f1f1'
        # Normal colors
        normal:
          black:   '0x212121'
          red:     '0xc30771'
          green:   '0x10a778'
          yellow:  '0xa89c14'
          blue:    '0x008ec4'
          magenta: '0x523c79'
          cyan:    '0x20a5ba'
          white:   '0xe0e0e0'
        # Bright colors
        bright:
          black:   '0x606060'
          red:     '0xfb007a'
          green:   '0x5fd7af'
          yellow:  '0xf3e430'
          blue:    '0x20bbfc'
          magenta: '0x6855de'
          cyan:    '0x4fb8cc'
          white:   '0xf1f1f1'

polybar:
  height: 27
