input * {
    accel_profile "flat"
}

output DP-3 {
    mode 2560x1440@165Hz
    pos 0 0
}
output DP-4 {
    mode 2560x1440@165Hz
    pos 2560 0
}
output DP-5 {
    mode 2560x1440@165Hz
    pos 5120 0
}
seat seat0 xcursor_theme Simp1e 48
font pango:DejaVu Sans 10
for_window [app_id="at.yrlf.wl_mirror"] floating enable
for_window [app_id="at.yrlf.wl_mirror"] border none
for_window [app_id="at.yrlf.wl_mirror"] resize set 144 50
for_window [app_id="at.yrlf.wl_mirror"] move position 3768 260
